apiVersion: v1
kind: ServiceAccount
metadata:
  name: gpu-webhook
  namespace: gpu-webhook
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gpu-webhook
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gpu-webhook
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gpu-webhook
subjects:
- kind: ServiceAccount
  name: gpu-webhook
  namespace: gpu-webhook
